//Console.WriteLine("Podaj racje żywnościowe :");
//string racje = Console.ReadLine()!;
//int racje1 = int.Parse(racje);
//Console.WriteLine("Podaj liczbę członków drużyny: ");
//string czlonkowie = Console.ReadLine()!;
//int czlonkowie1 = int.Parse(czlonkowie);
//Console.WriteLine("Podaj liczbę dni podróży: ");
//string dni = Console.ReadLine()!;
//int dni1 = int.Parse(dni);
//Console.WriteLine("Racje : " + racje1);
//Console.WriteLine("Członkowie drużyny : " + czlonkowie1);
//Console.WriteLine("Dni podróży : " + dni1);
//int ilePełychRacjiNaCzłonka = racje1 / czlonkowie1;
//int ileRacjiZostanie = racje1 % czlonkowie1;
//double ileRacjiDziennieNaCałąDrużynę = (double)racje1 / dni1;
//double ileRacjiDziennieNaCzłonka = (double)ileRacjiDziennieNaCałąDrużynę / czlonkowie1;
//Console.WriteLine("Ile pełnych racji na członka drużyny: " + ilePełychRacjiNaCzłonka);
//Console.WriteLine("Ile racji zostanie: " + ileRacjiZostanie);
//Console.WriteLine("Ile racji dziennie na całą drużynę: " + ileRacjiDziennieNaCałąDrużynę);
//Console.WriteLine("Ile racji dziennie na członka drużyny: " + ileRacjiDziennieNaCzłonka);